version: 99.0.{build}
skip_tags: true
os: Visual Studio 2017 RC
configuration: Release
environment:
  VisualStudioVersion: 15.0
build_script:
- ps: >-
    msbuild /nologo /m src\MoneyMan.sln /t:Restore,Build
test_script:
- ps: >-
    cd Nerdbank.MoneyManagement.Tests

    dotnet test
artifacts:
- path: src\**\*.nupkg
