version: '{build}'
skip_tags: true
os: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
build_script:
- msbuild /nologo /m src\MoneyMan.sln /t:Restore
- msbuild /nologo /m src\MoneyMan.sln /t:Build
test_script:
- cd Nerdbank.MoneyManagement.Tests
- dotnet test
artifacts:
- path: src\**\*.nupkg
