version: '{build}'
skip_tags: true
os: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
build_script:
- msbuild /nologo /m /v:quiet src\MoneyMan.sln /t:Restore
- msbuild /nologo /m /v:minimal src\MoneyMan.sln /t:Build,Pack
test_script:
- dotnet test src\Nerdbank.MoneyManagement.Tests\Nerdbank.MoneyManagement.Tests.csproj
artifacts:
- path: bin\**\*.nupkg
