parameters:
- name: windowsPool
  type: object
  default:
    vmImage: windows-2022
- name: includeMacOS

jobs:
- job: Windows
  pool: ${{ parameters.windowsPool }}
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml

  - powershell: '& (./azure-pipelines/Get-nbgv.ps1) cloud -c'
    displayName: ⚙ Set build number

  - template: dotnet.yml

- job: Linux
  pool:
    vmImage: Ubuntu 20.04
  variables:
    Platform: NonWindows
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml
  - template: dotnet.yml

- job: macOS
  condition: ${{ parameters.includeMacOS }}
  pool:
    vmImage: macOS-10.15
  variables:
    Platform: NonWindows
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml
  - template: dotnet.yml

- job: WrapUp
  dependsOn:
  - Windows
  - Linux
  - macOS
  pool: ${{ parameters.windowsPool }} # Use Windows agent because PublishSymbols task requires it (https://github.com/microsoft/azure-pipelines-tasks/issues/13821).
  condition: succeededOrFailed()
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml
    parameters:
      initArgs: -NoRestore
  - template: publish-symbols.yml
    parameters:
      includeMacOS: ${{ parameters.includeMacOS }}
  - template: publish-codecoverage.yml
    parameters:
      includeMacOS: ${{ parameters.includeMacOS }}
  - template: publish-deployables.yml
