trigger: none # We only want to trigger manually or based on resources
pr: none

resources:
  pipelines:
  - pipeline: CI
    source: MoneyMan
    trigger:
      tags:
      - auto-release

stages:
- stage: releasify
  displayName: squirrel releasify
  jobs:
  - job:
    variables:
      platform: win-x64
    steps:
    - template: install-dependencies.yml
    - powershell: Write-Host "##vso[build.updatebuildnumber]$(resources.pipeline.CI.runName)"
      displayName: Set pipeline name
    - download: CI
      artifact: deployables-Windows
      displayName: Download Squirrel input package
      patterns: 'deployables-Windows/SquirrelInputs/$(platform)/**'
    - task: S3Download@1
      displayName: Download releases from S3
      inputs:
        awsCredentials: AWS OSS AZP user
        regionName: us-west-1
        bucketName: moneyman-releases
        sourceFolder: prerelease/$(platform)
        globExpressions: |
          RELEASES
          *.nupkg
        targetFolder: $(Build.StagingDirectory)\s3
    - powershell: |
        $input = Get-ChildItem $(Pipeline.Workspace)/CI/deployables-Windows/SquirrelInputs/$(platform)/*.nupkg
        squirrel --releaseDir="$(Build.StagingDirectory)\s3" --no-msi --releasify $input
        ren $(Build.StagingDirectory)\s3\Setup.exe $(Build.StagingDirectory)\s3\Nerdbank.MoneyMan.Setup.exe -Force
      displayName: squirrel --releasify
    - publish:
      artifact: squirrelInstaller
    - task: S3Upload@1
      inputs:
        awsCredentials: AWS OSS AZP user
        regionName: us-west-1
        bucketName: moneyman-releases
        sourceFolder: $(Build.StagingDirectory)\s3
        globExpressions: |
          RELEASES
          *.exe
          Nerdbank.MoneyMan.*-*.nupkg
        targetFolder: prerelease/win-x64/
        filesAcl: public-read

- stage: GitHubRelease
  displayName: GitHub Release
  jobs:
  - deployment: create
    pool:
      vmImage: ubuntu-latest
    environment: No-Approval
    strategy:
      runOnce:
        deploy:
          steps:
          - task: GitHubRelease@1
            displayName: GitHub release (create)
            inputs:
              gitHubConnection: github.com_AArnott_OAuth
              repositoryName: $(Build.Repository.Name)
              target: $(resources.pipeline.CI.sourceCommit)
              tagSource: userSpecifiedTag
              tag: v$(resources.pipeline.CI.runName)
              title: v$(resources.pipeline.CI.runName)
              isDraft: true # After running this step, visit the new draft release, edit, and publish.
              changeLogCompareToRelease: lastNonDraftRelease
              changeLogType: issueBased
              changeLogLabels: |
                [
                  { "label" : "bug", "displayName" : "Fixes", "state" : "closed" },
                  { "label" : "enhancement", "displayName": "Enhancements", "state" : "closed" }
                ]

- stage: nuget_org
  displayName: nuget.org
  dependsOn: GitHubRelease
  condition: false # Suppress until it's worth sharing
  jobs:
  - deployment: push
    pool:
      vmImage: ubuntu-latest
    environment: No-Approval
    strategy:
      runOnce:
        deploy:
          steps:
          - download: CI
            artifact: deployables-Windows
            displayName: Download deployables-Windows artifact
            patterns: 'deployables-Windows/NuGet/*'
          - task: NuGetToolInstaller@1
            displayName: Use NuGet 5.x
            inputs:
              versionSpec: 5.x
          - task: NuGetCommand@2
            displayName: NuGet push
            inputs:
              command: push
              packagesToPush: $(Pipeline.Workspace)/CI/deployables-Windows/NuGet/*.nupkg
              nuGetFeedType: external
              publishFeedCredentials: nuget.org
